# Settings and secrets for the services, read by infra/host/deploy.sh into /opt/feedants/.env.
#
# Terraform owns the parameter names and the non-secret values it knows. Secret values are
# never in Terraform or its state: they start as CHANGE_ME placeholders and are set out of
# band, by scripts/generate-secrets.sh (generated ones) or by hand (provider credentials).
# deploy.sh refuses to deploy while any value is still CHANGE_ME.

locals {
  ssm_prefix = "/feedants/${var.environment}"

  # Known to Terraform; updated on every apply.
  managed_settings = {
    NODE_ENV                = "production"
    LOG_LEVEL               = "info"
    CORS_ORIGINS            = join(",", var.cors_origins)
    RABBITMQ_USER           = "feedants"
    S3_REGION               = var.region
    S3_BUCKET               = aws_s3_bucket.media.bucket
    S3_PUBLIC_BASE_URL      = "https://${aws_s3_bucket.media.bucket_regional_domain_name}"
    REDIS_URL               = "redis://redis:6379/0"
    JWKS_URL                = "http://identity:3001/.well-known/jwks.json"
    PAYMENT_PROVIDER        = "razorpay"
    OTEL_TRACES_SAMPLER_ARG = "1"
  }

  # Set by an operator; Terraform creates the placeholder and never overwrites it.
  operator_settings = [
    "SMTP_HOST", "SMTP_PORT", "SMTP_USER", "MAIL_FROM",
    "ALERT_EMAIL_TO", "ALERT_EMAIL_FROM", "RAZORPAY_KEY_ID",
  ]

  # Generated by scripts/generate-secrets.sh, or provider credentials set by hand.
  secrets = [
    "POSTGRES_PASSWORD", "IDENTITY_DB_PASSWORD", "COMPETITION_DB_PASSWORD", "PAYMENT_DB_PASSWORD",
    "NOTIFICATION_DB_PASSWORD", "RABBITMQ_PASSWORD", "INTERNAL_API_TOKEN", "OTP_PEPPER",
    "JWT_PRIVATE_KEY", "SMTP_PASSWORD", "RAZORPAY_KEY_SECRET", "RAZORPAY_WEBHOOK_SECRET",
  ]
}

resource "aws_ssm_parameter" "managed" {
  for_each = local.managed_settings
  name     = "${local.ssm_prefix}/${each.key}"
  type     = "String"
  # SSM rejects empty values; an empty CORS list becomes "-", which matches no origin.
  value = each.value == "" ? "-" : each.value
}

resource "aws_ssm_parameter" "operator" {
  for_each = toset(local.operator_settings)
  name     = "${local.ssm_prefix}/${each.key}"
  type     = "String"
  value    = "CHANGE_ME"

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "secret" {
  for_each = toset(local.secrets)
  name     = "${local.ssm_prefix}/${each.key}"
  type     = "SecureString"
  value    = "CHANGE_ME"

  lifecycle {
    ignore_changes = [value]
  }
}
